Repository wp-media/wp-rocket-e2e, pull requests merged in 2025-01, with the labels that each got.

#180 Fix #177 CPCSS notice has scenario that won't work correctly now due to the login structure
  config/wp.config.sample.ts
  src/support/steps/steps.ts
  utils/page-utils.ts
Labels: bug

#181 Closes #67: Only rename debug.log with errors relating to WPR
  src/support/hooks.ts
  utils/commands.ts
  utils/helpers.ts
Labels: enhancement

#182 Closes #140: Isolate VR Tests to be generic for all WPR features
  config/scenarioUrls.json
  package.json
  src/common/custom-world.ts
  src/features/visual-regression.feature
  src/support/hooks.ts
  src/support/steps/general.ts
Labels: enhancement

#200 Add a specific PR template, as per discussion with the team
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority: low
